export const TUNING_VALUES = {
    OVERALL_DAMAGE: 1.0,
    OVERALL_BASE_ENERGY_PER_SEC: 5.0,
    OVERALL_BASE_HEALTH: 14.0,

    DEATH_DAMAGE: 1.1,
    DECAY_DAMAGE: 1.0,
    UNDYING_DAMAGE_AND_VALUES: 1.0,
    ZUG_HEALTH_TUNING: 1.2,

    DEATH_ENERGY_TUNING: 2.0,
    REAP_DAMAGE: 1.0,
    REAP_ENERGY: 1.0,
    ZUG_DAMAGE: 1.0,
    ZUG_HEALTH: 1.0,

    DECAY_HEALTH_TUNING: 2.0,
}